name: estetify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.1.5
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.5
  flutter_facebook_auth: ^5.0.11
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo_estetify.png